### ISSUE TITLE
Некорректный ответ сервиса

### ISSUE THREAD

**Issue by mirecl** [r2r2/deposit#1]
При выполнении HTTP-запроса с payload:
```bash
{
   'amount': 15000, 
   'date': '01.01.2022', 
   'periods': 8, 
   'rate': 5.5,
}
```
... получаем некорректный ответ.

**Для проверки данных - необходимо воспользоваться файлом `example.xlsx`** (должен быть прислан вместе с ДЗ)

**Comment by r2r2** [comment]
Solved
