### ISSUE TITLE
Некорректный ответ сервиса

### ISSUE THREAD

**Issue by mirecl** [r2r2/deposit#5]
По issue https://github.com/r2r2/deposit/issues/1 не прошла повторная проверка.
Результат в `example.xlsx`:
<img src="https://user-images.githubusercontent.com/28476324/188488480-09a46cf5-740e-4107-964b-2d3df988caff.png" height="300">
Ответ сервиса:
![Screenshot 2022-09-05 at 18 25 24](https://user-images.githubusercontent.com/28476324/188488536-cfdc6583-6e42-4190-b251-004d33330e10.png)

**Расходятся даты!**

**Comment by r2r2** [comment]
Спасибо за Ваше терпение.
Почему-то думал, что надо считать выплаты именно на последний день месяца.
Исправил, теперь выводит корректные даты.
